-- Gamification System Schema (PostgreSQL/Supabase)

-- 1. Users & Progress
CREATE TABLE user_profiles (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name TEXT,
    current_xp INT DEFAULT 0,
    current_level INT DEFAULT 1,
    streak_days INT DEFAULT 0,
    last_activity_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Level Configuration (XP Table)
CREATE TABLE level_config (
    level INT PRIMARY KEY,
    xp_required INT NOT NULL,
    title TEXT
);

-- Seed basic levels
INSERT INTO level_config (level, xp_required, title) VALUES 
(1, 0, 'Novice SQL Learner'),
(2, 100, 'Select Statement Apprentice'),
(3, 300, 'Join Master'),
(4, 600, 'Subquery Specialist'),
(5, 1000, 'Database Architect'),
(6, 2000, 'Grandmaster of Optimization');

-- 3. Achievements
CREATE TABLE achievements (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    icon_name TEXT,
    xp_reward INT DEFAULT 50,
    condition_type TEXT
);

-- Seed Achievements
INSERT INTO achievements (id, title, description, icon_name, xp_reward) VALUES
('first_blood', 'ก้าวแรกสู่สังเวียน', 'ทำโจทย์สำเร็จครั้งแรก', 'Sword', 50),
('perfect_score_1', 'จอมแม่น 100%', 'ได้คะแนนเต็มใน 1 ชุดข้อสอบ', 'Target', 100),
('streak_3', 'ไฟแรงเฟร่อ', 'เข้าเรียนติดต่อกัน 3 วัน', 'Flame', 150),
('speed_demon', 'ปีศาจความเร็ว', 'ทำโจทย์ Mini Drill ครบใน 30 วินาที', 'Zap', 200);

-- 4. User Achievements (Unlocked)
CREATE TABLE user_achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES user_profiles(user_id),
    achievement_id TEXT NOT NULL REFERENCES achievements(id),
    unlocked_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE (user_id, achievement_id)
);

-- 5. User Activity Log (For Streak/Stats)
CREATE TABLE activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES user_profiles(user_id),
    activity_type TEXT,
    details JSONB,
    xp_earned INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
