-- Create Exam Results Table for Leaderboard
CREATE TABLE exam_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES user_profiles(user_id),
    exam_id TEXT NOT NULL, -- e.g., 'part1', 'mini_drill'
    score INT NOT NULL,
    max_score INT NOT NULL,
    time_taken_seconds INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Index for fast leaderboard queries
CREATE INDEX idx_exam_results_leaderboard ON exam_results (exam_id, score DESC, time_taken_seconds ASC);
